# Merges every per-PI bibliography in _bibliography/pi/*.bib into a single
# _bibliography/schema.bib, which jekyll-scholar reads (see _config.yml: scholar.bibliography).
#
# PIs only ever edit their own _bibliography/pi/<name>.bib file and commit it.
# The merged schema.bib is generated at build time and should NOT be edited by hand
# (it is listed in .gitignore).
#
# Grant tagging in zardini.bib: an entry may carry a custom `grants` field
# listing every grant that supported the work, comma- or semicolon-separated:
#
#   @article{someKey2026,
#     ...
#     grants = {schema, nsf-career, afosr-yfa}
#   }
#
# Only zardini.bib is filtered: its entries must include "schema" in `grants`
# (case-insensitive). All entries from other PI files are included, regardless
# of their grant tags. The `grants` field is stripped from every generated copy
# so it never appears in jekyll-scholar's "bibtex" popup. Original PI files
# are left unchanged.

require 'bibtex'

module Schema
  class BibMerger < Jekyll::Generator
    priority :highest
    safe false

    FILTERED_BIBLIOGRAPHY = 'zardini.bib'
    REQUIRED_GRANT       = 'schema'
    GRANT_FIELD          = :grants

    def generate(site)
      pi_dir   = File.join(site.source, '_bibliography', 'pi')
      out_file = File.join(site.source, '_bibliography', 'schema.bib')
      return unless Dir.exist?(pi_dir)

      files = Dir.glob(File.join(pi_dir, '*.bib')).sort
      merged = +"% AUTO-GENERATED by _plugins/merge_bib.rb — do not edit by hand.\n"
      merged << "% Source files: _bibliography/pi/*.bib\n\n"

      total_kept = 0

      files.each do |f|
        kept = schema_entries(f)
        total_kept += kept.size
        next if kept.empty?

        merged << "% ============================================================\n"
        merged << "% Source: #{File.basename(f)}\n"
        merged << "% ============================================================\n"
        kept.each { |entry| merged << entry.to_s << "\n\n" }
      end

      File.write(out_file, merged)
      Jekyll.logger.info "SCHEMA:", "merged #{total_kept} entr#{total_kept == 1 ? 'y' : 'ies'} " \
                                     "from #{files.size} PI bib file(s) -> _bibliography/schema.bib"
    end

    private

    # Filters grant tags only for zardini.bib, then returns copies of the
    # included entries with the grants field removed.
    def schema_entries(path)
      bib = BibTeX.open(path)
      entries = bib.select { |object| object.is_a?(BibTeX::Entry) }
      entries.select! { |entry| schema_tagged?(entry) } if File.basename(path) == FILTERED_BIBLIOGRAPHY

      entries.map { |entry| strip_grants(entry) }
    rescue BibTeX::ParseError => e
      Jekyll.logger.warn "SCHEMA:", "failed to parse #{path}: #{e.message}"
      []
    end

    def schema_tagged?(entry)
      return false unless entry.fields.key?(GRANT_FIELD)

      entry[GRANT_FIELD].to_s
                        .split(/[,;]/)
                        .map { |tag| tag.strip.downcase }
                        .include?(REQUIRED_GRANT)
    end

    def strip_grants(entry)
      copy = entry.dup
      copy.fields.delete(GRANT_FIELD)
      copy
    end
  end
end
